name: 🧪 Daily Benchmark

on:
  # 1️⃣ scheduled: every Wednesday at 05:00 UTC
  schedule:
    - cron: "0 5 * * 3"

  # 2️⃣ manual: button in the GitHub UI
  workflow_dispatch:

jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: apps/api

    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --only main

      - name: 🛡️ Run benchmark
        env:
          # Postgres connection string
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

          # GlueX plugin secrets
          GLUEX_API_KEY: ${{ secrets.GLUEX_API_KEY }}
          GLUEX_URL: ${{ secrets.GLUEX_URL }}
          GLUEX_UNIQUE_PID: ${{ secrets.GLUEX_UNIQUE_PID }}

          # LiqdSwap plugin secrets
          LIQDSWAP_URL: ${{ secrets.LIQDSWAP_URL }}

          # ZeroX plugin secrets
          ZEROX_URL: ${{ secrets.ZEROX_URL }}
          ZEROX_API_KEY: ${{ secrets.ZEROX_API_KEY }}

        run: |
          poetry run benchmark-run
